### PR TITLE
V1 API

### PR DESCRIPTION
**Pull request by domwong**
- API keys
- Usage tracking

See READMEs for design/impl

### CODE REVIEW

**Comment by domwong** [comment]
Current implementation of API key flow is somewhat of a result of the current constraints imposed by the way we have implemented namespacing etc. The biggest impact of this is on the fact that we're passing through the service auth from v1api downwards with the client's auth embedded as `Caller-Token`. This is clearly suboptimal but the current constraint is that you cannot call an endpoint in one namespace using a token issued by another unless you make it public. If we make an endpoint public then it can be called directly and thus a user could bypass the v1api. So we *could* just bite the bullet and allow cross namespace calling and leave it down to service implementers to make sure they check the JWT issuer is correct.

**Comment by asim** [comment]
LGTM. Only a few comments.

- Should we think about proper http path naming convention like `/v1/api/keys/{list, generate, ...}`. 
- Should we support any kind of rpc streaming right now as the micro api does
- Should we be caching store related use to speedup api calls
- How much work do we think cross namespace calling will take

**Comment by domwong** [comment]
> Should we think about proper http path naming convention like /v1/api/keys/{list, generate, ...}.

Yep, I think that makes sense. 

In the general case we just need to settle on a convention for how this gets routed. Given we need to extract a service name and a method name and optional grpc service name it probably makes sense to do 
- `/v1/api/keys/{list, generate, ...}` routes to `api` service `Keys.List` endpoint
- `/v1/helloworld/call` routes to `helloworld` service `Helloworld.Call` endpoint
Which I think is a convention that is used in the API anyway?

> Should we support any kind of rpc streaming right now as the micro api does
Not for this PR but as soon as we have an API where we'd like to do streaming then we can add it.

> Should we be caching store related use to speedup api calls
Eventually yes, I'd like to merge and deploy without first and do a bit of real world testing. Caching is hard so want to look at that as a separate PR 

> How much work do we think cross namespace calling will take
In theory very quick - I know the bit of code that stops it from happening right now in micro. Need to think about the implications and perhaps we could do something like adding an auth rule which you need to explicitly turn on for your namespace to allow callers from other namespaces

**Comment by asim** [comment]
> * `/v1/api/keys/{list, generate, ...}` routes to `api` service `Keys.List` endpoint
> * `/v1/helloworld/call` routes to `helloworld` service `Helloworld.Call` endpoint
>   Which I think is a convention that is used in the API anyway?

Yea that's right. We have some other ad-hoc logic for matching /v[0-9]+ along with extended names like /foo/bar/baz would be service foo with endpoint Bar.Baz but I think none of that is really important right now. If we can encapsulate the routing logic for what we deem as public facing APIs in this one service then we're in a good place.

**Pull request merged**
